### ISSUE TITLE
About your project

### ISSUE THREAD

**Issue by R00tS3c** [StratumPanel/Stratum-Panel#10]
In what stage is your project and can be VMs be reinstalled from your panel or that feature is in progress

**Comment by ericwang401** [comment]
Our project is still very much in early alpha.

The only available features are:
- Graphs
- Power functions
- Snapshots
- Edit server display name and disc
- Edit nameservers
- Edit hostname
- Edit BIOS
- Edit password
- a very very basic admin panel
